### ISSUE TITLE
关于文中表3的问题

### ISSUE THREAD

**Issue by HugoYu725** [zirui-yuan/MADG#1]
作者您好，我想请教一下您这篇文章中表3的实验是怎么设置的，希望能够得到您的解答，感谢！！！

**Comment by zirui-yuan** [comment]
表3 是10%异常情况下，对top k 的准确率和召回率的比较，是将 要评估的所有snapshot中的 所有motif 进行异常分数排序，取前k个进行计算得到。 和表2相比只是指标变了，参数设置是一样的。

**Comment by zirui-yuan** [comment]
> 作者您好，我想请教一下您这篇文章中表3的实验是怎么设置的，希望能够得到您的解答，感谢！！！

表3 是10%异常情况下，对top k 的准确率和召回率的比较，是将 要评估的所有snapshot中的 所有motif 进行异常分数排序，取前k个进行计算得到。 和表2相比只是指标变了，参数设置是一样的。

**Comment by HugoYu725** [comment]
> > 作者您好，我想请教一下您这篇文章中表3的实验是怎么设置的，希望能够得到您的解答，感谢！！！
> 
> 表3 是10%异常情况下，对top k 的准确率和召回率的比较，是将 要评估的所有snapshot中的 所有motif 进行异常分数排序，取前k个进行计算得到。 和表2相比只是指标变了，参数设置是一样的。

非常感谢您的耐心回复！我在运行您公开的代码的过程中发现，当代码中异常率p设置为10%时异常样本的总个数和表3计算所得不太一致，根据表3指标计算所得的异常个数普遍比异常率设置为10%时多出两倍，不知是否应当将异常率p设置为30%来得到表3的结果，衷心希望能得到您的帮助，再次感谢！！！

**Comment by zirui-yuan** [comment]
> > > 作者您好，我想请教一下您这篇文章中表3的实验是怎么设置的，希望能够得到您的解答，感谢！！！
> > 
> > 
> > 表3 是10%异常情况下，对top k 的准确率和召回率的比较，是将 要评估的所有snapshot中的 所有motif 进行异常分数排序，取前k个进行计算得到。 和表2相比只是指标变了，参数设置是一样的。
> 
> 非常感谢您的耐心回复！我在运行您公开的代码的过程中发现，当代码中异常率p设置为10%时异常样本的总个数和表3计算所得不太一致，根据表3指标计算所得的异常个数普遍比异常率设置为10%时多出两倍，不知是否应当将异常率p设置为30%来得到表3的结果，衷心希望能得到您的帮助，再次感谢！！！

你根据表3是无法计算出异常样本总数的啊，只能知道top k中有多少真异常。而异常样本总数是每个snapshot中的motif总数乘以异常率，这个得在程序中debug看。

**Comment by HugoYu725** [comment]
> > > > 作者您好，我想请教一下您这篇文章中表3的实验是怎么设置的，希望能够得到您的解答，感谢！！！
> > > 
> > > 
> > > 表3 是10%异常情况下，对top k 的准确率和召回率的比较，是将 要评估的所有snapshot中的 所有motif 进行异常分数排序，取前k个进行计算得到。 和表2相比只是指标变了，参数设置是一样的。
> > 
> > 
> > 非常感谢您的耐心回复！我在运行您公开的代码的过程中发现，当代码中异常率p设置为10%时异常样本的总个数和表3计算所得不太一致，根据表3指标计算所得的异常个数普遍比异常率设置为10%时多出两倍，不知是否应当将异常率p设置为30%来得到表3的结果，衷心希望能得到您的帮助，再次感谢！！！
> 
> 你根据表3是无法计算出异常样本总数的啊，只能知道top k中有多少真异常。而异常样本总数是每个snapshot中的motif总数乘以异常率，这个得在程序中debug看。

我是先用precision@k计算出topk中的异常样本个数，然后用这个个数除以recall@k得到异常样本总数的，我把表3用这个方法算到的异常样本总数和debug看的10%时的异常样本总数做了个比较，大约是多出两倍，所以在想是否应当将异常率p设置为30%来得到表3的结果，还望您指点一二！感谢！

**Comment by zirui-yuan** [comment]
> > > > > 作者您好，我想请教一下您这篇文章中表3的实验是怎么设置的，希望能够得到您的解答，感谢！！！
> > > > 
> > > > 
> > > > 表3 是10%异常情况下，对top k 的准确率和召回率的比较，是将 要评估的所有snapshot中的 所有motif 进行异常分数排序，取前k个进行计算得到。 和表2相比只是指标变了，参数设置是一样的。
> > > 
> > > 
> > > 非常感谢您的耐心回复！我在运行您公开的代码的过程中发现，当代码中异常率p设置为10%时异常样本的总个数和表3计算所得不太一致，根据表3指标计算所得的异常个数普遍比异常率设置为10%时多出两倍，不知是否应当将异常率p设置为30%来得到表3的结果，衷心希望能得到您的帮助，再次感谢！！！
> > 
> > 
> > 你根据表3是无法计算出异常样本总数的啊，只能知道top k中有多少真异常。而异常样本总数是每个snapshot中的motif总数乘以异常率，这个得在程序中debug看。
> 
> 我是先用precision@k计算出topk中的异常样本个数，然后用这个个数除以recall@k得到异常样本总数的，我把表3用这个方法算到的异常样本总数和debug看的10%时的异常样本总数做了个比较，大约是多出两倍，所以在想是否应当将异常率p设置为30%来得到表3的结果，还望您指点一二！感谢！

异常率应该是10%没错的。当初算recall的时候可能分母用成异常边数量了，导致rec@k都缩小了三倍。pre@k和rec@k应该都是所有snapshot综合起来 算出来的。

**Comment by zirui-yuan** [comment]
> > > > > 作者您好，我想请教一下您这篇文章中表3的实验是怎么设置的，希望能够得到您的解答，感谢！！！
> > > > 
> > > > 
> > > > 表3 是10%异常情况下，对top k 的准确率和召回率的比较，是将 要评估的所有snapshot中的 所有motif 进行异常分数排序，取前k个进行计算得到。 和表2相比只是指标变了，参数设置是一样的。
> > > 
> > > 
> > > 非常感谢您的耐心回复！我在运行您公开的代码的过程中发现，当代码中异常率p设置为10%时异常样本的总个数和表3计算所得不太一致，根据表3指标计算所得的异常个数普遍比异常率设置为10%时多出两倍，不知是否应当将异常率p设置为30%来得到表3的结果，衷心希望能得到您的帮助，再次感谢！！！
> > 
> > 
> > 你根据表3是无法计算出异常样本总数的啊，只能知道top k中有多少真异常。而异常样本总数是每个snapshot中的motif总数乘以异常率，这个得在程序中debug看。
> 
> 我是先用precision@k计算出topk中的异常样本个数，然后用这个个数除以recall@k得到异常样本总数的，我把表3用这个方法算到的异常样本总数和debug看的10%时的异常样本总数做了个比较，大约是多出两倍，所以在想是否应当将异常率p设置为30%来得到表3的结果，还望您指点一二！感谢！

异常率应该是10%没错的。但是表3当初算recall的时候可能分母用成异常边数量了，导致rec@k都缩小三倍。pre@k应该都没错，pre@k和rec@k都是所有snapshot综合起来 算出来的。感谢您的发现！！

**Comment by HugoYu725** [comment]
> > > > > > 作者您好，我想请教一下您这篇文章中表3的实验是怎么设置的，希望能够得到您的解答，感谢！！！
> > > > > 
> > > > > 
> > > > > 表3 是10%异常情况下，对top k 的准确率和召回率的比较，是将 要评估的所有snapshot中的 所有motif 进行异常分数排序，取前k个进行计算得到。 和表2相比只是指标变了，参数设置是一样的。
> > > > 
> > > > 
> > > > 非常感谢您的耐心回复！我在运行您公开的代码的过程中发现，当代码中异常率p设置为10%时异常样本的总个数和表3计算所得不太一致，根据表3指标计算所得的异常个数普遍比异常率设置为10%时多出两倍，不知是否应当将异常率p设置为30%来得到表3的结果，衷心希望能得到您的帮助，再次感谢！！！
> > > 
> > > 
> > > 你根据表3是无法计算出异常样本总数的啊，只能知道top k中有多少真异常。而异常样本总数是每个snapshot中的motif总数乘以异常率，这个得在程序中debug看。
> > 
> > 
> > 我是先用precision@k计算出topk中的异常样本个数，然后用这个个数除以recall@k得到异常样本总数的，我把表3用这个方法算到的异常样本总数和debug看的10%时的异常样本总数做了个比较，大约是多出两倍，所以在想是否应当将异常率p设置为30%来得到表3的结果，还望您指点一二！感谢！
> 
> 异常率应该是10%没错的。但是表3当初算recall的时候可能分母用成异常边数量了，导致rec@k都缩小三倍。pre@k应该都没错，pre@k和rec@k都是所有snapshot综合起来 算出来的。感谢您的发现！！



> > > > > > 作者您好，我想请教一下您这篇文章中表3的实验是怎么设置的，希望能够得到您的解答，感谢！！！
> > > > > 
> > > > > 
> > > > > 表3 是10%异常情况下，对top k 的准确率和召回率的比较，是将 要评估的所有snapshot中的 所有motif 进行异常分数排序，取前k个进行计算得到。 和表2相比只是指标变了，参数设置是一样的。
> > > > 
> > > > 
> > > > 非常感谢您的耐心回复！我在运行您公开的代码的过程中发现，当代码中异常率p设置为10%时异常样本的总个数和表3计算所得不太一致，根据表3指标计算所得的异常个数普遍比异常率设置为10%时多出两倍，不知是否应当将异常率p设置为30%来得到表3的结果，衷心希望能得到您的帮助，再次感谢！！！
> > > 
> > > 
> > > 你根据表3是无法计算出异常样本总数的啊，只能知道top k中有多少真异常。而异常样本总数是每个snapshot中的motif总数乘以异常率，这个得在程序中debug看。
> > 
> > 
> > 我是先用precision@k计算出topk中的异常样本个数，然后用这个个数除以recall@k得到异常样本总数的，我把表3用这个方法算到的异常样本总数和debug看的10%时的异常样本总数做了个比较，大约是多出两倍，所以在想是否应当将异常率p设置为30%来得到表3的结果，还望您指点一二！感谢！
> 
> 异常率应该是10%没错的。但是表3当初算recall的时候可能分母用成异常边数量了，导致rec@k都缩小三倍。pre@k应该都没错，pre@k和rec@k都是所有snapshot综合起来 算出来的。感谢您的发现！！

好嘞好嘞，非常感谢您的耐心解答，祝您生活愉快！！！
